'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bulma/css/bulma.min.css';
import '@/styles/variables.module.scss'
import '@/styles/appStyles.scss'
import { usePathname, useRouter } from 'next/navigation'
import { checkIsPublicRoute } from '@/functions/checkIsPublicRoute';
import PrivateRoute from '@/components/PrivateRoute/PrivateRoute';
import { useEffect } from 'react';
import "dotenv/config";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ContactsKeep',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { push } = useRouter();
  const pathname = usePathname();
  const isPublicPage = checkIsPublicRoute(pathname!);

  useEffect(() => {


    const token = localStorage.getItem("@ContactsKeep:TOKEN");


    if (pathname === "/" && token) {
      push("/Home");
    }
  }, []);

  return (
    <html lang="pt-br">
      
      <body className={inter.className + "reset bg-Dark min-h-100vh"}>
        {isPublicPage && children}
        {!isPublicPage && (<>
          <PrivateRoute>{children}</PrivateRoute>
        </>)}
        <script src="https://kit.fontawesome.com/06e82ab942.js" crossOrigin="anonymous"></script>
      </body>
      
    </html>
  )
}
